### ISSUE TITLE
Aes encryption load issue 

### ISSUE THREAD

**Issue by confirmed12** [aequabit/tcp-moe#16]
Got everything working just fine the issue is that %APIERROR% gets called on the /load route and I am 100% sure its because the aes 

$aes = new \MoeApi\Classes\Aes(null, $product->aesKey, 256);
    $aes->setData(file_get_contents(
        __DIR__.'/../dlls/'.$product->dllPath
    ));

    $app->response->write(base64_encode($aes->decrypt()));

Any help? ty

**Comment by DirtySenpai** [comment]
Don't encrypt your dll and replace the aes.php file with this one. https://hastebin.com/tufegugoye.xml
Works substantially better, and it's what aequabit suggested when I bugged him.

**Comment by confirmed12** [comment]
Got it working now it crashes with "Invalid DOS Header found in image"; :/


and no I'm not ecncrypting it

**Comment by 1tapboi** [comment]
Same issue here... Anyone can help?

**Comment by soultellegend** [comment]
Im getting same error and the hastebin link is not working

**Comment by soultellegend** [comment]
I have fixed all the errors but now Im getting Invalid DOS Header found in image 
searched on nternet but couldnt find any solutions

**Comment by soultellegend** [comment]
fixed that error too now my game is crashing when I inject the dll :/ I will try to fix it too

**Comment by soultellegend** [comment]
Fixed all the error and changed the injection method now all of them is working fine
