### ISSUE TITLE
One question

### ISSUE THREAD

**Issue by Frosteam** [aequabit/tcp-moe#3]
Hello!
Your work is simply gorgeous!

Can I do without the file composer.json?

**Comment by aequabit** [comment]
Download this: https://aqbt.pw/vendor.zip
And extract the "vendor" directory to the location, the composer.json is located in.

**Comment by Frosteam** [comment]
Thank you!

**Comment by Frosteam** [comment]
How can I make the download not an exe dll file?

**Comment by aequabit** [comment]
Could you explain what you're trying to do?

**Comment by Skiips** [comment]
Can you reup the vendor zip? My generated one is giving me a lot of errors about not finding stuff
