### ISSUE TITLE
How could i start the server on linux?

### ISSUE THREAD

**Issue by Rhaykoza** [aequabit/tcp-moe#4]

**Comment by aequabit** [comment]
You have to install Mono: http://www.mono-project.com/docs/getting-started/install/linux/

Then you have to make the server executable:
`$ chmod a+x tcp-moe-server.exe`

After that you start the server like this:
`$ mono tcp-moe-server.exe`

**Comment by Rhaykoza** [comment]
Thanks for your fast answer
