### ISSUE TITLE
Site files are not being installed.

### ISSUE THREAD

**Issue by sekabege** [aequabit/tcp-moe#8]
Site files are not being installed. Help me please :/

https://i.hizliresim.com/vbMGam.png

https://i.hizliresim.com/1LzbpY.png

https://i.hizliresim.com/Ly9Mva.png

**Comment by aequabit** [comment]
You have to point your webserver to the public directory.

**Comment by sekabege** [comment]
how will I do?

**Comment by sekabege** [comment]
Hey bro?
